"""Add enhanced user fields and email verification

Revision ID: 001
Revises:
Create Date: 2025-02-03

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_add_enhanced_user_fields'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns to users table
    op.add_column('users', sa.Column('full_name', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(100), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('verification_token', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(20), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(50), nullable=False, server_default='UTC'))
    op.add_column('users', sa.Column('preferred_currency', sa.String(10), nullable=False, server_default='USD'))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('telegram_notifications', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(100), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(50), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('subscription_plan', sa.String(50), nullable=False, server_default='FREE'))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))

    # Create indexes for verification and reset tokens
    op.create_index('ix_users_verification_token', 'users', ['verification_token'])
    op.create_index('ix_users_reset_token', 'users', ['reset_token'])

    # Update default status for new users
    op.execute("UPDATE users SET status = 'PENDING_VERIFICATION' WHERE status IS NULL OR status = 'ACTIVE'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes
    op.drop_index('ix_users_reset_token', table_name='users')
    op.drop_index('ix_users_verification_token', table_name='users')

    # Drop columns
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'subscription_plan')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'telegram_notifications')
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'preferred_currency')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'reset_expires_at')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'verification_expires_at')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'full_name')

    # ### end Alembic commands ###
